apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflare-token
spec:
  parameters:
    objects: |
      array:
      - |
        objectName: cloudflare-tunnel-token
        objectType: secret
        objectAlias: TUNNEL_TOKEN
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
  provider: azure
  secretObjects:
  - data:
    - key: TUNNEL_TOKEN
      objectName: TUNNEL_TOKEN
    secretName: cloudflare-token
    type: Opaque
