# chart.yaml
apiVersion: v2
name: my-chart
version: 1.0.0
description: A Helm chart for deploying MyApp
maintainers:
  - name: Your Name
    email: your-email@example.com
---
# values.yaml
replicaCount: 3
image:
  repository: my-app
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
